// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $github_username_ from "./routes/github/[username].tsx";
import * as $index from "./routes/index.tsx";
import * as $test from "./routes/test.tsx";
import * as $CocktailCollection from "./islands/CocktailCollection.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $IngredientFilterButton from "./islands/IngredientFilterButton.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/github/[username].tsx": $github_username_,
    "./routes/index.tsx": $index,
    "./routes/test.tsx": $test,
  },
  islands: {
    "./islands/CocktailCollection.tsx": $CocktailCollection,
    "./islands/Counter.tsx": $Counter,
    "./islands/IngredientFilterButton.tsx": $IngredientFilterButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
